// Listing of all the infrastructure unit tests
define([
	"./unit/Destroyable",
	"./unit/DisplayContainer",
	"./unit/register",
	"./unit/Widget-attr",
	"./unit/handlebars",
	"./unit/Widget-lifecycle",
	"./unit/Widget-placeAt",
	"./unit/Widget-utility",
	"./unit/HasDropDown",
	"./unit/CssState",
	"./unit/Container",
	"./unit/a11y",
	"./unit/Widget-on",
	"./unit/Stateful",
	"./unit/Selection",
	"./unit/StoreMap",
	"./unit/Store",
	"./unit/Scrollable"
]);
