// Listing of all the infrastructure unit tests
define([
	"./theme",
	"./DisplayContainer",
	"./register",
	"./CustomElement",
	"./Widget",
	"./handlebars",
	"./CssState",
	"./Container",
	"./a11y",
	"./uacss",
	"./Selection",
	"./StoreMap",
	"./Store",
	"./Scrollable",
	"./KeyNav",
	"./FormWidget",
	"./FormValueWidget"
]);
